### PR TITLE
Feature/mac m1 build

### PR DESCRIPTION
**Pull request by andrewpatto**
Package bumping that got `pip` install working on my mac M1

### CODE REVIEW

**Comment by andrewpatto** [comment]
No need for merging - just is basically a place where I can store any changes I note along the ways. Feel free to integrate (or not integrate) them into your main branch through whatever processes you normally use

**Comment by TheMadBug** [comment]
Nice, will wait until we branch off a stable deploy branch for the next deploy (should be next week) then can merge this in.

**Comment by andrewpatto** [comment]
The build fix for htseq got release 50 minutes ago - so I got lucky there with my timing!

**Comment by TheMadBug** [comment]
I uses this as a basis to update requirements.txt myself. I'm now running off venv instead of conda, so that's cleaning up the dependenciesquite a bit.

**Pull request closed without merging**
